### PR TITLE
Sir, committing Test base,Login page, Home page,login test case, logout test case and Helper to branch Shraddha_TL.

### PR DESCRIPTION
**Pull request by ShraddhaM90**
Sir, 
I have committed testBase so plz review.

Regards,
Shraddha

### CODE REVIEW

**Comment by VasantChavan** [comment]
Hi Shradha,

Kindly update discussed changes in your test cases and page layer.

Kindly add validation for each test cases.

Regards,
Vasant

**Comment by ShraddhaM90** [comment]
Sir, I have committed ExcelDataProvider and Capture Screenshot plz review.
Regard,
Shraddha

**Comment by VasantChavan** [comment]
you can merger this code with master .

Regards,
Vasant

**Comment by VasantChavan** [comment]
Hi Shradha,

Please update changes and send for review.

Regards,
Vasant

**Pull request closed without merging**
